/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public\100cmWideFrame.glb --types --output src/components/modelcomponent/100cmFrame.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
type GLTFAction = any;
type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
  }
  materials: {
    ['Material.008']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Largeframe(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/100cmWideFrame.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.Cube.geometry}
      material={materials['Material.008']}
      rotation={[Math.PI / 2, 0, 0]}
      scale={[0.359, 0.171, 0.185]}
    />
  </group>
)
}

useGLTF.preload('/100cmWideFrame.glb')
export default Largeframe;