/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public\Fdrawer.glb --types --output src/components/modelcomponent/Fdrawer.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
type GLTFAction = any;
type GLTFResult = GLTF & {
  nodes: {
    Lades: THREE.Mesh
  }
  materials: {
    ['FrontColor.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Fdrawer(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Fdrawer.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Lades.geometry} material={materials['FrontColor.001']} position={[1.52, 0.257, 5.745]} rotation={[Math.PI / 2, 0, 0]} scale={0.038} />
    </group>
  )
}

useGLTF.preload('/Fdrawer.glb')

export default Fdrawer;
