/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/new75cmframe.glb --types --output src/components/modelcomponent/new75cmFrame.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
type GLTFAction = any;
type GLTFResult = GLTF & {
  nodes: {
    Mesh2: THREE.Mesh
  }
  materials: {
    ['FrontColor.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Mediumframe(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/new75cmframe.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh2.geometry} material={materials['FrontColor.001']} position={[-2, 1.5, 1]} scale={0.0024} />
    </group>
  )
}

useGLTF.preload('/new75cmframe.glb')
export default Mediumframe;
