/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/newcornerframe.glb --types --output src/components/modelcomponent/newCornerFrame.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
type GLTFAction = any;
type GLTFResult = GLTF & {
  nodes: {
    Mesh3: THREE.Mesh
  }
  materials: {
    ['FrontColor.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Cornerframe(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/newcornerframe.glb') as GLTFResult
  const material = materials['FrontColor.001'].clone();

  // Set the material color to grey
  material.color.set('white');

  // Set the roughness to 1 for a fully matte appearance
  material.roughness = 1;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh3.geometry} material={materials['FrontColor.001']} position={[-2, 1.5, 1]} scale={0.0024} />
    </group>
  )
}

useGLTF.preload('/newcornerframe.glb')

export default Cornerframe;